### ISSUE TITLE
Components Re-render when used with frost-modal on same page

### ISSUE THREAD

**Issue by Owlman145** [ciena-frost/ember-frost-tabs#81] opened 2018-01-29 23:08 UTC
Frost-tab components get re-rendered multiple times when frost-modal on the same application page are activated/deactivated. This issue is probably related to the fact that they both use ember-elsewhere.

**Comment by notmessenger** [comment] 2018-01-30 13:05
JIRA: FROST-1235

**Comment by notmessenger** [comment] 2018-01-30 13:19
@Owlman145 Can you please provide additional information about the setup you are using when you encounter this issue?

* What version of Ember CLI are you using when consuming this add-on?
* What version of Ember are you using when consuming this add-on?
* What version of this repo (`ember-frost-tabs`) are you using?
  * Please run `npm ls <package-name>` in the terminal in the directory for the code base where you are seeing this to gather that information.
* What version of `ember-frost-modal` are you using?
  * Please run `npm ls <package-name>` in the terminal in the directory for the code base where you are seeing this to gather that information.
* How is the multiple re-rendering manifesting itself?  How do you know it is be re-rendered multiple times?
* Are you able to provide a screen recording of this occurrence?
* Can you point us to an instance of code where this is occurring so we can see the full setup that is in place?  As it is likely that this will be internal code against a private codebase hit us up in `#frost-support` to provide this info.
* Is this reproducible on any other page in the app?

**Comment by Owlman145** [comment] 2018-01-30 17:12
Versions:
 - ember-cli: 2.12.3
 - ember-frost-tabs: 7.0.1 (was initially on 5.4.1 and updated in an attempt to fix issue)
 - ember-frost-modal: 6.2.13
It will re-render exactly twice when the modal is opened and once when it is closed.
The re-render is manifested by the component going through its On Re-Render Lifecycle (didUpdateAttrs(), didReceiveAttrs(), etc.). In my case this causes spurious chart animations and database requests.
The steps to reproduce are as simple as having a component with a didReceiveAttrs() function inside a frost-tab, and a simple frost-modal that uses a frost-modal-outlet anywhere on the page.

**Comment by notmessenger** [comment] 2018-01-31 18:40
@Owlman145 using `ember-cli@2.12.3`, `ember-frost-tabs@^7.0.1`, and `ember-frost-modal@^9.0.0` along with the code contained below I am unable to replicate the behavior you have described.   I do not know if it is because this has been fixed in a subsequent version of `ember-frost-modal` or more likely because you do not have uniquely-named usages of `{{frost-modal-outlet}}` but the code below can be used to guide you to the correct usage of these components.


<details>
 <summary>app/components/more-content.js</summary>

```js
import Ember from 'ember';

export default Ember.Component.extend({
});
```
</details>

<details>
 <summary>app/templates/components/more-content.hbs</summary>

```hbs
This is content
```
</details>

<details>
 <summary>app/components/tab-component.js</summary>

```js
import Ember from 'ember';

export default Ember.Component.extend({

    didReceiveAttrs () {
        this._super(...arguments)

        console.log('didReceiveAttrs() called')
    },

    didRender () {
        this._super(...arguments)

        console.log('didRender() called')
    },

    didUpdateAttrs () {
        this._super(...arguments)

        console.log('didUpdateAttrs() called')
    }

});

```
</details>

<details>
 <summary>app/templates/components/tab-content.hbs</summary>

```hbs
text: {{text}}
```
</details>

<details>
 <summary>app/controllers/applications.js</summary>

```js
import Ember from 'ember';

export default Ember.Controller.extend({
  queryParams: [
    'isModalVisible',
    'isModal2Visible'
  ],

  isModalVisible: false,
  isModal2Visible: false,


  selectedTab: 'template',
  actions: {
    onChange (tabId) {
      this.set('selectedTab', tabId)
    }
  }

});
```
</details>

<details>
 <summary>app/templates/application.hbs</summary>

```hbs
{{frost-modal-outlet
  name='modalTest'
}}

{{frost-modal-warn-message
  cancel=(hash
    isVisible=false
  )
  confirm=(hash
    text='GAAH!'
  )
  isVisible=isModalVisible
  noBlur=true
  targetOutlet='modalTest'
  title='BAMF'
  onClose=(action (mut isModalVisible) false)
}}

{{frost-button
  hook='launchButton'
  priority='primary'
  size='medium'
  text='Launch frost-modal-warn-message modal'
  onClick=(action (mut isModalVisible) true)
}}

{{frost-modal-outlet
  name='targetedModal'
}}

{{frost-modal-binding 'more-content'
  closeOnOutsideClick=true
  targetOutlet='targetedModal'
  isVisible=isModal2Visible
  onClose=(action (mut isModal2Visible) false)
}}

<br><br>
{{frost-button
  hook='launchButton'
  priority='primary'
  size='medium'
  text='Launch frost-modal-binding modal'
  onClick=(action (mut isModal2Visible) true)
}}

<br><br>
{{frost-tabs
  hook='myTabs'
  selectedTab=selectedTab
  onChange=(action 'onChange')
  tabs=(array
    (component 'frost-tab'
      id='template'
      text='Template'
      content=(component 'tab-component' text='template'))
    (component 'frost-tab'
      id='controller'
      text='Controller'
      content=(component 'tab-component' text='controller'))
    (component 'frost-tab'
      id='route'
      text='Route'
      content=(component 'tab-component' text='route'))
    (component 'frost-tab'
      id='css'
      text='CSS'
      disabled=true
      content=(component 'tab-component' text='CSS'))
  )
}}

```
</details>

**Closed as completed by notmessenger** 2018-01-31 18:40 UTC
Labels: bug, invalid, JIRA
